### ISSUE TITLE
World crash when loaded

### ISSUE THREAD

**Issue by frcnetto** [MikeLydeamore/ExNihiloAdscensio#104]
When I try to load my single player world the game crashes. I have the exnihiloadscensio-1.10.2-0.1.12 in a FTB Sky Factory 3 modpack
log:
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_111]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_111]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1045) [bcx.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371) [bcx.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NullPointerException
	at exnihiloadscensio.networking.MessageCheckLight$MessageCheckLightHandler.lambda$onMessage$9(MessageCheckLight.java:54) ~[MessageCheckLight$MessageCheckLightHandler.class:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_111]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
	... 9 more

**Comment by threehams** [comment]
I'm also getting a crash on load with this exception in the logs, but a working backup from 2 hours earlier has the same callstack (with no crash). I don't think this mod is the cause.
