### ISSUE TITLE
Barrel Crash

### ISSUE THREAD

**Issue by NegativePanda1** [MikeLydeamore/ExNihiloAdscensio#105]
HI i am getting a crash when joining a server due to a barrel render issue. Any idea how i can fix it please ?

Log below

// I just don't know what went wrong :(
 
Time: 24/02/17 18:17
Description: Rendering Block Entity
 
java.lang.NullPointerException: Rendering Block Entity
    at exnihiloadscensio.barrel.modes.block.BarrelModeBlock.getTextureForRender(BarrelModeBlock.java:100)
    at exnihiloadscensio.client.renderers.RenderBarrel.renderTileEntityAt(RenderBarrel.java:40)
    at exnihiloadscensio.client.renderers.RenderBarrel.func_180535_a(RenderBarrel.java:16)
    at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_178469_a(TileEntityRendererDispatcher.java:147)
    at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:125)
    at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:701)
    at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1315)
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1229)
    at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1038)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
 
 
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
 
-- Head --
Thread: Client thread
Stacktrace:
    at exnihiloadscensio.barrel.modes.block.BarrelModeBlock.getTextureForRender(BarrelModeBlock.java:100)
    at exnihiloadscensio.client.renderers.RenderBarrel.renderTileEntityAt(RenderBarrel.java:40)
    at exnihiloadscensio.client.renderers.RenderBarrel.func_180535_a(RenderBarrel.java:16)
 
-- Block Entity Details --
Details:
    Name: blockBarrel1 // exnihiloadscensio.tiles.TileBarrel
    Block type: ID #320 (tile.blockBarrel0 // exnihiloadscensio.blocks.BlockBarrel)
    Block data value: 0 / 0x0 / 0b0000
    Block location: World: (449281,65,3881), Chunk: (at 1,4,9 in 28080,242; contains blocks 449280,0,3872 to 449295,255,3887), Region: (877,7; contains chunks 28064,224 to 28095,255, blocks 449024,0,3584 to 449535,255,4095)
    Actual block type: ID #320 (tile.blockBarrel0 // exnihiloadscensio.blocks.BlockBarrel)
    Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
    at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_178469_a(TileEntityRendererDispatcher.java:147)
    at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:125)
    at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:701)
    at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1315)
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1229)
 
-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityPlayerSP['Negative_Panda'/2181, l='MpServer', x=449278.98, y=64.00, z=3843.00]]
    Chunk stats: MultiplayerChunkCache: 121, 121
    Level seed: 0
    Level generator: ID 06 - botania-skyblock, ver 0. Features enabled: false
    Level generator options:
    Level spawn location: World: (25,89,-67), Chunk: (at 9,5,13 in 1,-5; contains blocks 16,0,-80 to 31,255,-65), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
    Level time: 70327805 game time, 51107352 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
    Forced entities: 21 total; [EntitySkeleton['Skeleton'/2336, l='MpServer', x=449317.50, y=4.00, z=3833.50], EntityZombie['Zombie'/2337, l='MpServer', x=449317.50, y=4.00, z=3833.50], EntityWitch['Witch'/2338, l='MpServer', x=449317.50, y=4.00, z=3836.50], EntityCreeper['Creeper'/2339, l='MpServer', x=449317.50, y=4.00, z=3834.50], EntityZombie['Zombie'/2340, l='MpServer', x=449317.50, y=4.00, z=3835.50], EntityZombie['Zombie'/2341, l='MpServer', x=449317.50, y=4.00, z=3835.50], EntityCreeper['Creeper'/2342, l='MpServer', x=449317.50, y=4.00, z=3836.50], EntityHuman['miznobody'/2343, l='MpServer', x=449309.50, y=4.00, z=3835.50], EntityHuman['Etho'/2344, l='MpServer', x=449306.20, y=4.00, z=3835.83], EntityHuman['msrevenge103'/2345, l='MpServer', x=449309.50, y=4.00, z=3833.50], EntityHuman['EricBrian'/2346, l='MpServer', x=449305.50, y=4.00, z=3833.50], EntityZombie['Zombie'/2347, l='MpServer', x=449306.56, y=4.00, z=3836.66], EntityZombie['Zombie'/2348, l='MpServer', x=449308.82, y=4.00, z=3833.82], EntitySkeleton['Skeleton'/2349, l='MpServer', x=449308.50, y=4.00, z=3836.50], EntityHuman['MHF_LavaSlime'/2350, l='MpServer', x=449305.50, y=4.00, z=3834.50], EntityPlayerSP['Negative_Panda'/2181, l='MpServer', x=449278.98, y=64.00, z=3843.00], EntityCow['Cow'/2330, l='MpServer', x=449239.88, y=64.00, z=3841.06], EntityCow['Cow'/2331, l='MpServer', x=449241.55, y=64.00, z=3844.19], EntityCow['Cow'/2332, l='MpServer', x=449244.56, y=64.00, z=3841.63], EntitySheep['Sheep'/2333, l='MpServer', x=449245.55, y=64.00, z=3842.20], EntityZombie['Zombie'/2335, l='MpServer', x=449317.50, y=4.00, z=3835.50]]
    Retry entities: 0 total; []
    Server brand: fml,forge,sponge
    Server type: Non-integrated multiplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:415)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:392)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by NegativePanda1** [comment]
Anyone know how i can fix this and be able to use this server ? It happens as soon as the render starts when i join this server.

**Comment by Flabort** [comment]
1) Holy wall of text why didn't you use pastebin
2) Are you using the same versions of the mods as the server? EG you may be using the newest version of a modpack while the server is a version behind, or vice versa.
3) Are you using Optifine? If so, remove it. If not, you're going to have to wait on a more official response.

**Comment by NegativePanda1** [comment]
hah sorry pastbin next time :)

All versions were the same and the barrel that was causing it had to be removed. It even crashed the server admin when he came to my island.

**Comment by MikeLydeamore** [comment]
Hopefully fixed in d7fd5f3f0b77dd40f2ae6a65cfb17f169b249a92
Please reopen if issue persists.
